export enum ECalculatorPageLocalStorageKey {
  SUM_DEPOSIT = 'CALCULATOR_PAGE:SUM_DEPOSIT',
  STOPLOSS_PRICE = 'CALCULATOR_PAGE:STOPLOSS_PRICE',
  INSTRUMENT_PRICE = 'CALCULATOR_PAGE:INSTRUMENT_PRICE',
  ALLOWED_LOSS_PERCENT_PER_DEPOSIT = 'CALCULATOR_PAGE:ALLOWED_LOSS_PERCENT_PER_DEPOSIT',
};
